### ISSUE TITLE
can´t update - log inside

### ISSUE THREAD

**Issue by demlak** [pimatic/pimatic-ds18b20#3]
can´t update.. and now the plugin does not work at all.. no temp-updates.. and coresponding rules get error

see log:

> \# npm install pimatic-ds18b20
npm http GET https://registry.npmjs.org/pimatic-ds18b20
npm http 200 https://registry.npmjs.org/pimatic-ds18b20
npm http GET https://registry.npmjs.org/pimatic-ds18b20/-/pimatic-ds18b20-0.8.4.tgz
npm http 200 https://registry.npmjs.org/pimatic-ds18b20/-/pimatic-ds18b20-0.8.4.tgz
npm http GET https://registry.npmjs.org/ds18b20/0.0.3
npm http 404 https://registry.npmjs.org/ds18b20/0.0.3
npm ERR! Error: version not found: 0.0.3 : ds18b20/0.0.3
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

> npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-ds18b20"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/pimatic-app/npm-debug.log
npm ERR! not ok code 0

**Comment by sweetpi** [comment]
See pimatic/pimatic#593 for updates.
